### ISSUE TITLE
419 (unknown status) Error at multiple locations

### ISSUE THREAD

**Issue by philippelorange** [PaulL48/SOEN341-SC4#67]
The 419 (unknown status) error happens at the following locations, when the user is not logged in:

- On the login page, after clicking on the "Ask a question" button as a guest and trying to log in;
- When trying to vote on a question after signing in, and signing out.

**Steps to reproduce**

1. Log into website
2. Log out of website
3. Click on the vote up or vote down button on any question, and verify console

**Comment by frodinm** [comment]
When this issue happens, did you check the network tab when you inspect? If you didn't, it might provide more info on the reason for the 419 response.

**Comment by philippelorange** [comment]
error no longer occuring, closing issue.
