### ISSUE TITLE
Bug: Login from "Ask Question" does not work

### ISSUE THREAD

**Issue by MarlinTheWiz** [PaulL48/SOEN341-SC4#73]
If user isn't logged in and clicks "ask question", they are redirected to login page, from there login will not work

**Comment by frodinm** [comment]
In this case, the csrf token is the issue. Laravel needs to generate a fresh token every time which can be achieved by reloading the browser. One way is to use the function window.location.href = "/Login" instead of this.props.history.push("/Login")

**Comment by philippelorange** [comment]
Issue has been fixed in prior sprint.
